version: "3.8"

services:
  spark-iceberg:
    image: tabulario/spark-iceberg
    container_name: spark-iceberg
    networks:
      iceberg_net:
    depends_on:
      - rest
      - minio
    volumes:
      - ./warehouse:/home/iceberg/warehouse
      - ./notebooks:/home/iceberg/notebooks/notebooks
      - ./data:/home/iceberg/data
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    ports:
      - "8888:8888"
      - "8080:8080"
      - "10000:10000"
      - "10001:10001"
  rest:
    image: tabulario/iceberg-rest
    container_name: iceberg-rest
    networks:
      iceberg_net:
    ports:
      - "8181:8181"
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - CATALOG_WAREHOUSE=s3a://warehouse/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio:9000
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    networks:
      iceberg_net:
        aliases:
          - warehouse.minio
    ports:
      - "9001:9001"
      - "9000:9000"
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
       - minio_data:/data
  mc:
    depends_on:
      - minio
    image: minio/mc
    container_name: mc
    networks:
      iceberg_net:
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    volumes:
      - ./init-minio.sh:/init-minio.sh
    entrypoint: [ "/bin/sh", "-c", "/init-minio.sh" ]
  ui:
    build: ./ui
    ports:
      - "3000:3000"
    volumes:
      - ./ui/src:/ui/src
      - /ui/src/node_modules
    stdin_open: true
    tty: true
    container_name: caspian-ui
    depends_on:
      - fastapi_app
  fastapi_app:
    image: caspian-back-end 
    build: ./app
    container_name: fastapi_app
    ports:
      - "8090:8090"
    networks:
      iceberg_net:
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    depends_on:
      - spark-iceberg
      - minio
      - mongodb
    volumes:
      - ./data:/home/iceberg/data  # Assuming you want to access data from the FastAPI app
      - ./app/api:/app/api
  mongodb:
    image: 'mongo'
    volumes:
      - ./data:/data/mongo-db
    env_file:
      - ./env/mongo.env
    container_name: mongodb
volumes:
  minio_data:
networks:
  iceberg_net:
    driver: bridge
