global:
  scrape_interval: 10s # short interval for manual testing

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Add a job for Pushgateway
  - job_name: 'pushgateway_metrics'
    static_configs:
      - targets: ['localhost:9091']