name: UI Tests
on:
  pull_request:
    paths:
      - 'ui/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get UI
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 21
      - name: Install dependencies
        run: |
          cd ui/
          yarn --frozen-lockfile
      - name: run ui tests
        run: |
          cd ui
          yarn test